### ISSUE TITLE
RuntimeError: Tensors must be CUDA and dense

### ISSUE THREAD

**Issue by zyms5244** [skyhehe123/SA-SSD#17]
when run ./dist_train.sh RuntimeError raised:

```
[40, 1600, 1408]
2020-04-22 09:30:45,407 - INFO - Distributed training: True
2020-04-22 09:30:45,407 - INFO - Set random seed to 0
[40, 1600, 1408]
Traceback (most recent call last):
  File "./train.py", line 130, in <module>
    main()
  File "./train.py", line 81, in main
    model = MMDistributedDataParallel(model).cuda()
  File "/root/miniconda3/envs/pcdet/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 298, in __init__
    self.broadcast_bucket_size)
  File "/root/miniconda3/envs/pcdet/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 480, in _distributed_broadcast_coalesced
    dist._broadcast_coalesced(self.process_group, tensors, buffer_size)
RuntimeError: Tensors must be CUDA and dense
Traceback (most recent call last):
  File "./train.py", line 130, in <module>
    main()
  File "./train.py", line 81, in main
    model = MMDistributedDataParallel(model).cuda()
  File "/root/miniconda3/envs/pcdet/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 298, in __init__
    self.broadcast_bucket_size)
  File "/root/miniconda3/envs/pcdet/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 480, in _distributed_broadcast_coalesced
    dist._broadcast_coalesced(self.process_group, tensors, buffer_size)
RuntimeError: Tensors must be CUDA and dense
Traceback (most recent call last):
  File "/root/miniconda3/envs/pcdet/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/miniconda3/envs/pcdet/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/envs/pcdet/lib/python3.7/site-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/root/miniconda3/envs/pcdet/lib/python3.7/site-packages/torch/distributed/launch.py", line 242, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/root/miniconda3/envs/pcdet/bin/python', '-u', './train.py', '--local_rank=1', '../configs/car_cfg.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

```

My Environment
CUDA 10.0+CUDNN 7.6
python=3.7
spconv=1.0
pytorch=1.2.0(1.1.0 also raised the same error)

Could you give me some suggestions?

**Comment by zyms5244** [comment]
solved

**Comment by stalkermustang** [comment]
@zyms5244 how you solve this?

**Comment by weweus** [comment]
@zyms5244

Could you please give me some suggestion? I have the same problem.

**Comment by oby-yang** [comment]
how to solve it??

**Comment by tyjiang1997** [comment]
how to solve it?? @zyms5244
