### ISSUE TITLE
KeyError: 'model_state'        -----      evaluate the the pretrained model

### ISSUE THREAD

**Issue by jlqzzz** [skyhehe123/SA-SSD#19]
I download the pretrained model, and evaluate the model:
cd tools
python3 test.py ../configs/car_cfg.py ../saved_model_vehicle/epoch_50.pth

Then the error occur:

==> Loading parameters from checkpoint ../saved_model_vehicle/epoch_50.pth to GPU
Traceback (most recent call last):
  File "test.py", line 159, in <module>
    main()
  File "test.py", line 141, in main
    load_params_from_file(model, args.checkpoint)
  File "/home/zzz/SA-SSD/tools/train_utils/__init__.py", line 157, in load_params_from_file
    model_state_disk = checkpoint['model_state']
KeyError: 'model_state'

Does anyone know how to solve this problem? Thank you very much!

**Comment by stalkermustang** [comment]
You should change key to load model.
Print checkpoint.keys() first to see options, and choice right one.
BTW after that you got load weights problem, caused my DataParallel apply - easy add 'model.' at the start of weights alias/key in OrderedDict in model state.

**Comment by mengxingshifen1218** [comment]
> I download the pretrained model, and evaluate the model:
> cd tools
> python3 test.py ../configs/car_cfg.py ../saved_model_vehicle/epoch_50.pth
> 
> Then the error occur:
> 
> ==> Loading parameters from checkpoint ../saved_model_vehicle/epoch_50.pth to GPU
> Traceback (most recent call last):
> File "test.py", line 159, in
> main()
> File "test.py", line 141, in main
> load_params_from_file(model, args.checkpoint)
> File "/home/zzz/SA-SSD/tools/train_utils/**init**.py", line 157, in load_params_from_file
> model_state_disk = checkpoint['model_state']
> KeyError: 'model_state'
> 
> Does anyone know how to solve this problem? Thank you very much!

I also meet this problem. Have you solved it ?

**Comment by stalkermustang** [comment]
https://github.com/skyhehe123/SA-SSD/issues/19#issuecomment-619886333 @mengxingshifen1218

**Comment by mengxingshifen1218** [comment]
> [#19 (comment)](https://github.com/skyhehe123/SA-SSD/issues/19#issuecomment-619886333) @mengxingshifen1218

thank you！

**Comment by ipie2050** [comment]
"You should change key to load model.
Print checkpoint.keys() first to see options, and choice right one.
BTW after that you got load weights problem, caused my DataParallel apply - easy add 'model.' at the start of weights alias/key in OrderedDict in model state."

Can you make the second part  clearer? Namely, how do you exactly modify the following:

-------------------------------------------------
def model_state_to_cpu(model_state):
    model_state_cpu = type(model_state)()  # ordered dict
    for key, val in model_state.items():
        model_state_cpu[key] = val.cpu()
    return model_state_cpu
-------------------------------------------------

Thanks.

**Comment by ipie2050** [comment]
@mengxingshifen1218: 
Can you share how to solve your model_state issue using the comment [#19 (comment) ](https://github.com/skyhehe123/SA-SSD/issues/19#issuecomment-619886333) from 
@stalkermustang? Thanks.

**Comment by mengxingshifen1218** [comment]
> @mengxingshifen1218:
> Can you share how to solve your model_state issue using the comment [#19 (comment) ](https://github.com/skyhehe123/SA-SSD/issues/19#issuecomment-619886333) from
> @stalkermustang? Thanks.

You can train this model by yourself，it will be ok.

**Comment by dimitree54** [comment]
Check [my answer](https://github.com/skyhehe123/SA-SSD/issues/49#issuecomment-728733137) at duplicate issue. I have provided code to load pretrained model without any training there.
