### ISSUE TITLE
Train Error

### ISSUE THREAD

**Issue by chenxyyy** [skyhehe123/SA-SSD#4]
Hi!  Thank you for your great work！

But I have met some problem when I use this work.

> root@679e1e925e7e:/data/SA-SSD/tools# python train.py ../configs/car_cfg.py 
Traceback (most recent call last):
  File "train.py", line 7, in <module>
    from mmdet.datasets import get_dataset
  File "/data/SA-SSD/mmdet/datasets/__init__.py", line 1, in <module>
    from .custom import CustomDataset
  File "/data/SA-SSD/mmdet/datasets/custom.py", line 10, in <module>
    from .utils import to_tensor, random_scale
  File "/data/SA-SSD/mmdet/datasets/utils.py", line 12, in <module>
    from mmdet.core.point_cloud import voxel_generator
  File "/data/SA-SSD/mmdet/core/__init__.py", line 1, in <module>
    from .anchor import *  # noqa: F401, F403
  File "/data/SA-SSD/mmdet/core/anchor/__init__.py", line 2, in <module>
    from .anchor_target import anchor_target
  File "/data/SA-SSD/mmdet/core/anchor/anchor_target.py", line 2, in <module>
    from ..bbox import assign_and_sample, BBoxAssigner, SamplingResult, bbox2delta, rbbox3d2delta
  File "/data/SA-SSD/mmdet/core/bbox/__init__.py", line 2, in <module>
    from .assignment import BBoxAssigner, AssignResult
  File "/data/SA-SSD/mmdet/core/bbox/assignment.py", line 4, in <module>
    from mmdet.ops.iou3d import iou3d_utils
  File "/data/SA-SSD/mmdet/ops/__init__.py", line 1, in <module>
    from .points_op import pts_in_boxes3d
  File "/data/SA-SSD/mmdet/ops/points_op/__init__.py", line 2, in <module>
    from mmdet.ops.points_op import points_op_cpu
ImportError: /data/SA-SSD/mmdet/ops/points_op/points_op_cpu.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c1019UndefinedTensorImpl10_singletonE

Could you please tell me how to fix this error?

**Comment by skyhehe123** [comment]
> Hi! Thank you for your great work！
> 
> But I have met some problem when I use this work.
> 
> > root@679e1e925e7e:/data/SA-SSD/tools# python train.py ../configs/car_cfg.py
> > Traceback (most recent call last):
> > File "train.py", line 7, in 
> > from mmdet.datasets import get_dataset
> > File "/data/SA-SSD/mmdet/datasets/**init**.py", line 1, in 
> > from .custom import CustomDataset
> > File "/data/SA-SSD/mmdet/datasets/custom.py", line 10, in 
> > from .utils import to_tensor, random_scale
> > File "/data/SA-SSD/mmdet/datasets/utils.py", line 12, in 
> > from mmdet.core.point_cloud import voxel_generator
> > File "/data/SA-SSD/mmdet/core/**init**.py", line 1, in 
> > from .anchor import *  # noqa: F401, F403
> > File "/data/SA-SSD/mmdet/core/anchor/**init**.py", line 2, in 
> > from .anchor_target import anchor_target
> > File "/data/SA-SSD/mmdet/core/anchor/anchor_target.py", line 2, in 
> > from ..bbox import assign_and_sample, BBoxAssigner, SamplingResult, bbox2delta, rbbox3d2delta
> > File "/data/SA-SSD/mmdet/core/bbox/**init**.py", line 2, in 
> > from .assignment import BBoxAssigner, AssignResult
> > File "/data/SA-SSD/mmdet/core/bbox/assignment.py", line 4, in 
> > from mmdet.ops.iou3d import iou3d_utils
> > File "/data/SA-SSD/mmdet/ops/**init**.py", line 1, in 
> > from .points_op import pts_in_boxes3d
> > File "/data/SA-SSD/mmdet/ops/points_op/**init**.py", line 2, in 
> > from mmdet.ops.points_op import points_op_cpu
> > ImportError: /data/SA-SSD/mmdet/ops/points_op/points_op_cpu.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c1019UndefinedTensorImpl10_singletonE
> 
> Could you please tell me how to fix this error?

Have you compile the points_op.cpp?

**Comment by chenxyyy** [comment]
Yes , I have compile the points_op.cpp!

```
$ cd mmdet/ops/points_op
$ python3 setup.py build_ext --inplace
```

**Comment by skyhehe123** [comment]
what is pytorch version

**Comment by chenxyyy** [comment]
I use the pytorch1.0  CUDA10.1

**Comment by skyhehe123** [comment]
I guess the error is resulted from the incompatible environment. I am using pytorch 1.1 and python 3.7.

**Comment by skyhehe123** [comment]
I remember at::Tensor is used in pytorch 1.1 while in old version they use THCudaTensor

**Comment by chenxyyy** [comment]
OK. Thank you! I will try!

**Comment by chenxyyy** [comment]
Hi  @skyhehe123 . Thank you  for your answer! I have solved the above problem. 

But when I train the data,  the window keeps prompting errors ```cudahash: Completely failed to build```

> root@674c174bbb81:/data/SA-SSD/tools# python train.py ../configs/car_cfg.py 
2020-03-26 08:39:35,890 - INFO - Distributed training: False
[40, 1600, 1408]
load 14357 Car database infos
After filter database:
load 13442 Car database infos
2020-03-26 08:39:40,140 - INFO - Start running, host: root@674c174bbb81, work_dir: /data/SA-SSD/saved_model_vehicle
2020-03-26 08:39:40,141 - INFO - workflow: [('train', 1)], max: 50 epochs
2020-03-26 08:39:53,757 - INFO - Epoch [1][1/3712]	lr: 0.00333, eta: 29 days, 5:52:04, time: 13.614, data_time: 9.299, memory: 943, aux_loss_cls: 0.6027, aux_loss_reg: 1.9651, rpn_loc_loss: 6.0134, rpn_cls_loss: 27.8855, rpn_dir_loss: 0.1263, loss_cls: 126.9466, loss: 163.5396
cudahash: Completely failed to build
2020-03-26 08:39:59,307 - INFO - Epoch [1][2/3712]	lr: 0.00335, eta: 20 days, 14:01:28, time: 5.551, data_time: 4.625, memory: 1085, aux_loss_cls: 0.7112, aux_loss_reg: 2.2128, rpn_loc_loss: 9.6448, rpn_cls_loss: 60.1833, rpn_dir_loss: 0.1764, loss_cls: 300.8033, loss: 373.7318
cudahash: Completely failed to build
2020-03-26 08:40:07,828 - INFO - Epoch [1][3/3712]	lr: 0.00336, eta: 19 days, 19:45:20, time: 8.520, data_time: 7.676, memory: 1085, aux_loss_cls: 0.6987, aux_loss_reg: 2.6371, rpn_loc_loss: 6.1246, rpn_cls_loss: 51.3174, rpn_dir_loss: 0.1810, loss_cls: 242.0629, loss: 303.0217


When I ran ```python test.py ../configs/car_cfg.py ../saved_model_vehicle/epoch_50.pth``` , I met the same error.

> [40, 1600, 1408]
[                                                  ] 1/3769, 0.2 task/s, elapsed: 6s, ETA: 21374scudahash: Completely failed to build
[                                                  ] 3/3769, 0.4 task/s, elapsed: 7s, ETA:  9254scudahash: Completely failed to build
[                                                  ] 5/3769, 0.4 task/s, elapsed: 12s, ETA:  9180scudahash: Completely failed to build
[                                                  ] 6/3769, 0.4 task/s, elapsed: 15s, ETA:  9156scudahash: Completely failed to build
[                                                  ] 7/3769, 0.4 task/s, elapsed: 17s, ETA:  9150scudahash: Completely failed to build
[                                                  ] 9/3769, 0.4 task/s, elapsed: 22s, ETA:  9087scudahash: Completely failed to build
[                                                  ] 12/3769, 0.4 task/s, elapsed: 29s, ETA:  8990scudahash: Completely failed to build
[                                                  ] 13/3769, 0.4 task/s, elapsed: 31s, ETA:  8990scudahash: Completely failed to build
[                                                  ] 14/3769, 0.4 task/s, elapsed: 34s, ETA:  9002scudahash: Completely failed to build
[                                                  ] 15/3769, 0.4 task/s, elapsed: 36s, ETA:  8972scudahash: Completely failed to build
[                                                  ] 18/3769, 0.4 task/s, elapsed: 43s, ETA:  8958scudahash: Completely failed to build
[                                                  ] 19/3769, 0.4 task/s, elapsed: 45s, ETA:  8950scudahash: Completely failed to build


My ```spconv``` version is 1.1, but not 1.0. Is the problem of ```spconv```?

**Comment by skyhehe123** [comment]
Yes, make sure you have installed CUDPP when you compiling spconv.

**Comment by chenxyyy** [comment]
OK！I will fix this problem and then I will learn your code in detail, thanks again.

**Comment by chenxyyy** [comment]
Hello！ When I run the test code ```python test.py ../configs/car_cfg.py ../saved_model_vehicle/epoch_50.pth```, I met the following error.

> root@674c174bbb81:/data/SA-SSD/tools# python test.py ../configs/car_cfg.py ../saved_model_vehicle/epoch_50.pth 
> /data/SA-SSD/tools/test.py(135)main()
-> args = parse_args()
(Pdb) c
> /data/SA-SSD/tools/test.py(144)main()
-> dataset = utils.get_dataset(cfg.data.val)
(Pdb) c
> /data/SA-SSD/mmdet/datasets/utils.py(83)get_dataset()
-> if isinstance(data_cfg['ann_file'], (list, tuple)):
(Pdb) c
> /data/SA-SSD/tools/test.py(146)main()
-> class_names = cfg.data.val.class_names
(Pdb) c
[40, 1600, 1408]
[>>>>>                                             ] 1/9, 0.2 task/s, elapsed: 5s, ETA:    37scudahash: Completely failed to build
[>>>>>>>>>>>>>>>>                                  ] 3/9, 0.6 task/s, elapsed: 5s, ETA:    10scudahash: Completely failed to build
[>>>>>>>>>>>>>>>>>>>>>>>>>>>                       ] 5/9, 0.7 task/s, elapsed: 7s, ETA:     6scudahash: Completely failed to build
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>                 ] 6/9, 0.8 task/s, elapsed: 8s, ETA:     4scudahash: Completely failed to build
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>            ] 7/9, 0.7 task/s, elapsed: 10s, ETA:     3scudahash: Completely failed to build
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 9/9, 0.7 task/s, elapsed: 12s, ETA:     0sTraceback (most recent call last):
  File "test.py", line 192, in <module>
    main()
  File "test.py", line 146, in main
    class_names = cfg.data.val.class_names
  File "/data/SA-SSD/mmdet/core/evaluation/kitti_eval.py", line 829, in get_official_eval_result
    gt_annos, dt_annos, current_classes, min_overlaps, compute_aos, difficultys)
  File "/data/SA-SSD/mmdet/core/evaluation/kitti_eval.py", line 698, in do_eval_v2
    min_overlaps, compute_aos)
  File "/data/SA-SSD/mmdet/core/evaluation/kitti_eval.py", line 576, in eval_class_v3
    rets = calculate_iou_partly(dt_annos, gt_annos, metric, num_parts)
  File "/data/SA-SSD/mmdet/core/evaluation/kitti_eval.py", line 366, in calculate_iou_partly
    gt_boxes = np.concatenate([a["bbox"] for a in gt_annos_part], 0)
ValueError: need at least one array to concatenate

Then I debuge the code, I found that this error occured in ```mmdet/core/evaluation/kitti_eval.py : def calculate_iou_partly()```, I don't know the actual effect of the function of ```mmdet/core/evaluation/kitti_eval.py : def get_split_parts(num, num_part): ```

Could you please tell me how to fix this error?

**Comment by chenxyyy** [comment]
Hello!  When I ran python test.py ../configs/car_cfg.py ../saved_model_vehicle/epoch_50.pth , I met the following error.

> root@674c174bbb81:/data/SA-SSD/tools# python test.py ../configs/car_cfg.py ../saved_model_vehicle/epoch_50.pth 
> /data/SA-SSD/tools/test.py(135)main()
-> args = parse_args()
(Pdb) c
> /data/SA-SSD/tools/test.py(144)main()
-> dataset = utils.get_dataset(cfg.data.val)
(Pdb) c
> /data/SA-SSD/mmdet/datasets/utils.py(83)get_dataset()
-> if isinstance(data_cfg['ann_file'], (list, tuple)):
(Pdb) c
> /data/SA-SSD/tools/test.py(146)main()
-> class_names = cfg.data.val.class_names
(Pdb) c
[40, 1600, 1408]
[>>>>>                                             ] 1/9, 0.2 task/s, elapsed: 4s, ETA:    35scudahash: Completely failed to build
[>>>>>>>>>>>>>>>>                                  ] 3/9, 0.6 task/s, elapsed: 5s, ETA:    10scudahash: Completely failed to build
[>>>>>>>>>>>>>>>>>>>>>>>>>>>                       ] 5/9, 0.7 task/s, elapsed: 7s, ETA:     6scudahash: Completely failed to build
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>                 ] 6/9, 0.9 task/s, elapsed: 7s, ETA:     3scudahash: Completely failed to build
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>            ] 7/9, 0.8 task/s, elapsed: 9s, ETA:     3scudahash: Completely failed to build
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 9/9, 0.8 task/s, elapsed: 11s, ETA:     0s> /data/SA-SSD/mmdet/core/evaluation/kitti_eval.py(356)calculate_iou_partly()
Traceback (most recent call last):
  File "test.py", line 192, in <module>
    main()
  File "test.py", line 166, in main
    result = get_official_eval_result(gt_annos, outputs, current_classes=class_names)
  File "/data/SA-SSD/mmdet/core/evaluation/kitti_eval.py", line 832, in get_official_eval_result
    gt_annos, dt_annos, current_classes, min_overlaps, compute_aos, difficultys)
  File "/data/SA-SSD/mmdet/core/evaluation/kitti_eval.py", line 708, in do_eval_v2
    min_overlaps)
  File "/data/SA-SSD/mmdet/core/evaluation/kitti_eval.py", line 579, in eval_class_v3
    rets = calculate_iou_partly(dt_annos, gt_annos, metric, num_parts)
  File "/data/SA-SSD/mmdet/core/evaluation/kitti_eval.py", line 387, in calculate_iou_partly
    overlap_part = bev_box_overlap(gt_boxes, dt_boxes).astype(
  File "/data/SA-SSD/mmdet/core/evaluation/kitti_eval.py", line 126, in bev_box_overlap
    riou = rotate_iou_gpu_eval(boxes, qboxes, criterion)
  File "/data/SA-SSD/mmdet/core/post_processing/rotate_nms_gpu.py", line 608, in rotate_iou_gpu_eval
    box_dtype = boxes.dtype
TypeError: 'function' object is not subscriptable

When I debuge the code, I found that the code ```mmdet/core/post_processing/rotate_nms_gpu.py : def rotate_iou_gpu_eval(boxes, query_boxes, criterion=-1, device_id=0):``` exits error.
```
def rotate_iou_gpu_eval(boxes, query_boxes, criterion=-1, device_id=0):
   # 
   # ……
   # 
    with stream.auto_synchronize():
        boxes_dev = cuda.to_device(boxes.reshape([-1]), stream)
        query_boxes_dev = cuda.to_device(query_boxes.reshape([-1]), stream)
        iou_dev = cuda.to_device(iou.reshape([-1]), stream)
        rotate_iou_kernel_eval[blockspergrid, threadsPerBlock, stream](
            N, K, boxes_dev, query_boxes_dev, iou_dev, criterion)
        iou_dev.copy_to_host(iou.reshape([-1]), stream=stream)
```

Is it correct to write the function ```rotate_iou_kernel_eval``` like that?

How can I fix this error?

**Comment by dongqiaqia** [comment]
> Hi @skyhehe123 . Thank you for your answer! I have solved the above problem.
> 
> But when I train the data, the window keeps prompting errors `cudahash: Completely failed to build`
> 
> > root@674c174bbb81:/data/SA-SSD/tools# python train.py ../configs/car_cfg.py
> > 2020-03-26 08:39:35,890 - INFO - Distributed training: False
> > [40, 1600, 1408]
> > load 14357 Car database infos
> > After filter database:
> > load 13442 Car database infos
> > 2020-03-26 08:39:40,140 - INFO - Start running, host: root@674c174bbb81, work_dir: /data/SA-SSD/saved_model_vehicle
> > 2020-03-26 08:39:40,141 - INFO - workflow: [('train', 1)], max: 50 epochs
> > 2020-03-26 08:39:53,757 - INFO - Epoch [1][1/3712]	lr: 0.00333, eta: 29 days, 5:52:04, time: 13.614, data_time: 9.299, memory: 943, aux_loss_cls: 0.6027, aux_loss_reg: 1.9651, rpn_loc_loss: 6.0134, rpn_cls_loss: 27.8855, rpn_dir_loss: 0.1263, loss_cls: 126.9466, loss: 163.5396
> > cudahash: Completely failed to build
> > 2020-03-26 08:39:59,307 - INFO - Epoch [1][2/3712]	lr: 0.00335, eta: 20 days, 14:01:28, time: 5.551, data_time: 4.625, memory: 1085, aux_loss_cls: 0.7112, aux_loss_reg: 2.2128, rpn_loc_loss: 9.6448, rpn_cls_loss: 60.1833, rpn_dir_loss: 0.1764, loss_cls: 300.8033, loss: 373.7318
> > cudahash: Completely failed to build
> > 2020-03-26 08:40:07,828 - INFO - Epoch [1][3/3712]	lr: 0.00336, eta: 19 days, 19:45:20, time: 8.520, data_time: 7.676, memory: 1085, aux_loss_cls: 0.6987, aux_loss_reg: 2.6371, rpn_loc_loss: 6.1246, rpn_cls_loss: 51.3174, rpn_dir_loss: 0.1810, loss_cls: 242.0629, loss: 303.0217
> 
> When I ran `python test.py ../configs/car_cfg.py ../saved_model_vehicle/epoch_50.pth` , I met the same error.
> 
> > [40, 1600, 1408]
> > [                                                  ] 1/3769, 0.2 task/s, elapsed: 6s, ETA: 21374scudahash: Completely failed to build
> > [                                                  ] 3/3769, 0.4 task/s, elapsed: 7s, ETA:  9254scudahash: Completely failed to build
> > [                                                  ] 5/3769, 0.4 task/s, elapsed: 12s, ETA:  9180scudahash: Completely failed to build
> > [                                                  ] 6/3769, 0.4 task/s, elapsed: 15s, ETA:  9156scudahash: Completely failed to build
> > [                                                  ] 7/3769, 0.4 task/s, elapsed: 17s, ETA:  9150scudahash: Completely failed to build
> > [                                                  ] 9/3769, 0.4 task/s, elapsed: 22s, ETA:  9087scudahash: Completely failed to build
> > [                                                  ] 12/3769, 0.4 task/s, elapsed: 29s, ETA:  8990scudahash: Completely failed to build
> > [                                                  ] 13/3769, 0.4 task/s, elapsed: 31s, ETA:  8990scudahash: Completely failed to build
> > [                                                  ] 14/3769, 0.4 task/s, elapsed: 34s, ETA:  9002scudahash: Completely failed to build
> > [                                                  ] 15/3769, 0.4 task/s, elapsed: 36s, ETA:  8972scudahash: Completely failed to build
> > [                                                  ] 18/3769, 0.4 task/s, elapsed: 43s, ETA:  8958scudahash: Completely failed to build
> > [                                                  ] 19/3769, 0.4 task/s, elapsed: 45s, ETA:  8950scudahash: Completely failed to build
> 
> My `spconv` version is 1.1, but not 1.0. Is the problem of `spconv`?

Hi, I tried both spconv 1.1 and spconv1.0. Message 'cudahash: completely failed to build'  dosen't occur in sponv1.0.

**Comment by skyhehe123** [comment]
@dongqiaqia Yes, the spconv is 1.0.  By the way, can you reproduce my results?

**Comment by dongqiaqia** [comment]
> @dongqiaqia Yes, the spconv is 1.0. By the way, can you reproduce my results?

I cannot reproduce your results. And the training log is not consistent with yours. I don't know what's wrong. 
Here is my results:
Car AP@0.70, 0.70, 0.70:
bbox AP:95.42, 80.26, 75.76
bev  AP:93.37, 80.40, 78.10
3d   AP:85.76, 70.49, 66.14
aos  AP:95.36, 80.09, 75.47
Car AP@0.70, 0.50, 0.50:
bbox AP:95.42, 80.26, 75.76
bev  AP:96.73, 86.20, 83.90
3d   AP:95.85, 80.81, 78.32
aos  AP:95.36, 80.09, 75.47

Environment:
pytorch1.3
cuda 10.1
cudnn 7.6
python3.7
spconv1.1

And Model in an environment with spconv1.0 is training. The log seems the same as spconv1.1.
[20200330.log](https://github.com/skyhehe123/SA-SSD/files/4406486/20200330.log)

**Comment by skyhehe123** [comment]
@dongqiaqia The loss looks exactly different than mines. Let me check it first. Maybe a docker env. is needed.

**Comment by stalkermustang** [comment]
> @dongqiaqia The loss looks exactly different than mines. Let me check it first. Maybe a docker env. is needed.

hello. I'm starting to work with your repo, and Docker is a nice idea. Can you briefly describe system (cuda, cudnn, spconv commit, pytorch exact version, python version)? i try to build and train, also try to use method on WaymoOpen dataset

**Comment by abhigoku10** [comment]
@skyhehe123 @chenxyyy  @dongqiaqia i tried to install spconv 1.0 but was not successful in installing since i did not find the package can you please share the link or process to install spconv 1.0??
Henceforth i installed pytorch 1.3 python3.69  spconv1.1 and cuda 10.0 but i am getting the same error as @chenxyyy can you please let me knw how you solved this environment dependencies  

@skyhehe123  can we run this inference code in CPU ??? what changes should be made 

THanks in advance
