### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by hughlee815** [skyhehe123/SA-SSD#58]
大佬们：
我在运行test.py的时候报了这个错：
`Traceback (most recent call last):
  File "test.py", line 163, in <module>
    main()
  File "test.py", line 158, in main
    result = get_official_eval_result(gt_annos, outputs, current_classes=class_names)
  File "/home/nio/pointdet/SA-SSD/mmdet/core/evaluation/kitti_eval.py", line 829, in get_official_eval_result
    gt_annos, dt_annos, current_classes, min_overlaps, compute_aos, difficultys)
  File "/home/nio/pointdet/SA-SSD/mmdet/core/evaluation/kitti_eval.py", line 698, in do_eval_v2
    min_overlaps, compute_aos)
  File "/home/nio/pointdet/SA-SSD/mmdet/core/evaluation/kitti_eval.py", line 576, in eval_class_v3
    rets = calculate_iou_partly(dt_annos, gt_annos, metric, num_parts)
  File "/home/nio/pointdet/SA-SSD/mmdet/core/evaluation/kitti_eval.py", line 371, in calculate_iou_partly
    [a["location"][:, [0, 2]] for a in gt_annos_part], 0)
  File "<__array_function__ internals>", line 6, in concatenate
**ValueError: need at least one array to concatenate**
`
请大佬们帮忙看看，感激不尽

**Comment by hughlee815** [comment]
Traceback (most recent call last):
  File "test.py", line 163, in <module>
    main()
  File "test.py", line 158, in main
    result = get_official_eval_result(gt_annos, outputs, current_classes=class_names)
  File "/home/nio/pointdet/SA-SSD/mmdet/core/evaluation/kitti_eval.py", line 829, in get_official_eval_result
    gt_annos, dt_annos, current_classes, min_overlaps, compute_aos, difficultys)
  File "/home/nio/pointdet/SA-SSD/mmdet/core/evaluation/kitti_eval.py", line 698, in do_eval_v2
    min_overlaps, compute_aos)
  File "/home/nio/pointdet/SA-SSD/mmdet/core/evaluation/kitti_eval.py", line 576, in eval_class_v3
    rets = calculate_iou_partly(dt_annos, gt_annos, metric, num_parts)
  File "/home/nio/pointdet/SA-SSD/mmdet/core/evaluation/kitti_eval.py", line 371, in calculate_iou_partly
    [a["location"][:, [0, 2]] for a in gt_annos_part], 0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
Segmentation fault (core dumped)

**Comment by chenxyyy** [comment]
遇到了相同的问题, 解决方案如下:

```
 # /data/SA-SSD-master/mmdet/core/evaluation/kitti_eval.py: line549
def eval_class_v3(gt_annos,
                  dt_annos,
                  current_classes,
                  difficultys,
                  metric,
                  min_overlaps,
                  compute_aos=False,
                  num_parts=50):

# 将num_parts=50 改为num_parts=1
```
