### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by hitxing** [skyhehe123/SA-SSD#85]
Thanks for the great work ! My enviornment as follows:
CUDA10.0  torch1.1.0  torchvision0.3.0  python3.6.5  spconv1.0 cmake3.16.0 
Evaluate the model is OK, however, when I try to train a model by run the script "python3 train.py ../configs/car_cfg.py" , An error was encountered:
(SASSD) weixing@weixing:~/deeplearning/projects/SA-SSD/tools$ python3 train.py ../configs/car_cfg.py
/home/weixing/anaconda3/envs/SASSD/lib/python3.6/site-packages/numba/cuda/envvars.py:17: NumbaWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated and consequently ignored, found use of NUMBAPRO_CUDA_DRIVER=/usr/lib/x86_64-linux-gnu/libcuda.so.

For more information about alternatives visit: ('https://numba.pydata.org/numba-doc/latest/cuda/overview.html', '#cudatoolkit-lookup')
  warnings.warn(errors.NumbaWarning(msg))
/home/weixing/anaconda3/envs/SASSD/lib/python3.6/site-packages/numba/cuda/envvars.py:17: NumbaWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated and consequently ignored, found use of NUMBAPRO_NVVM=/usr/local/cuda/nvvm/lib64/libnvvm.so.

For more information about alternatives visit: ('https://numba.pydata.org/numba-doc/latest/cuda/overview.html', '#cudatoolkit-lookup')
  warnings.warn(errors.NumbaWarning(msg))
/home/weixing/anaconda3/envs/SASSD/lib/python3.6/site-packages/numba/cuda/envvars.py:17: NumbaWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated and consequently ignored, found use of NUMBAPRO_LIBDEVICE=/usr/local/cuda/nvvm/libdevice.

For more information about alternatives visit: ('https://numba.pydata.org/numba-doc/latest/cuda/overview.html', '#cudatoolkit-lookup')
  warnings.warn(errors.NumbaWarning(msg))
2020-12-07 10:37:17,116 - INFO - Distributed training: False
[40, 1600, 1408]
load 28742 Car database infos
After filter database:
load 21375 Car database infos
/home/weixing/anaconda3/envs/SASSD/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py:168: UserWarning: Runner was deprecated, please use EpochBasedRunner instead
  'Runner was deprecated, please use EpochBasedRunner instead')
/home/weixing/anaconda3/envs/SASSD/lib/python3.6/site-packages/mmcv/runner/base_runner.py:59: UserWarning: batch_processor is deprecated, please implement train_step() and val_step() in the model instead.
  warnings.warn('batch_processor is deprecated, please implement '
Traceback (most recent call last):
  File "train.py", line 101, in <module>
    main()
  File "train.py", line 94, in main
    logger=logger)
  File "/home/weixing/deeplearning/projects/SA-SSD/mmdet/apis/train.py", line 60, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/weixing/deeplearning/projects/SA-SSD/mmdet/apis/train.py", line 114, in _non_dist_train
    cfg.log_level)
  File "/home/weixing/anaconda3/envs/SASSD/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 169, in __init__
    super().__init__(*args, **kwargs)
  File "/home/weixing/anaconda3/envs/SASSD/lib/python3.6/site-packages/mmcv/runner/base_runner.py", line 79, in __init__
    f'optimizer must be a dict of torch.optim.Optimizers, '
TypeError: optimizer must be a dict of torch.optim.Optimizers, but optimizer["type"] is a <class 'str'>

Did someone encounter with the same problem? Could you please point me how to fix it?

**Comment by vehxianfish** [comment]
@hitxing .Hi,Do you solve this question? thank you.
