### ISSUE TITLE
raise RuntimeError(MISSING_LIBDEVICE_FILE_MSG.format(arch=arch)) RuntimeError: Missing libdevice file for compute_50. Please ensure you have package cudatoolkit 7.5. Install package by:      conda install cudatoolkit=7.5

### ISSUE THREAD

**Issue by sherlockzym** [skyhehe123/SA-SSD#87]
(ssd) root@logic:~/SA-SSD# python tools/create_data.py
Traceback (most recent call last):
  File "tools/create_data.py", line 8, in <module>
    from mmdet.core.bbox3d.geometry import remove_outside_points, points_in_rbbox, box_camera_to_lidar
  File "/root/SA-SSD/mmdet/core/__init__.py", line 1, in <module>
    from .anchor import *  # noqa: F401, F403
  File "/root/SA-SSD/mmdet/core/anchor/__init__.py", line 2, in <module>
    from .anchor_target import anchor_target
  File "/root/SA-SSD/mmdet/core/anchor/anchor_target.py", line 2, in <module>
    from ..bbox import assign_and_sample, BBoxAssigner, SamplingResult, bbox2delta, rbbox3d2delta
  File "/root/SA-SSD/mmdet/core/bbox/__init__.py", line 2, in <module>
    from .assignment import BBoxAssigner, AssignResult
  File "/root/SA-SSD/mmdet/core/bbox/assignment.py", line 3, in <module>
    from mmdet.core.bbox3d import region_similarity
  File "/root/SA-SSD/mmdet/core/bbox3d/region_similarity.py", line 23, in <module>
    from mmdet.core.post_processing.rotate_nms_gpu import rotate_iou_gpu, rotate_iou_gpu_eval
  File "/root/SA-SSD/mmdet/core/post_processing/__init__.py", line 3, in <module>
    from .rotate_nms_gpu import rotate_nms_gpu
  File "/root/SA-SSD/mmdet/core/post_processing/rotate_nms_gpu.py", line 22, in <module>
    @cuda.jit('(int64, float32, float32[:, :], uint64[:])')
  File "/root/anaconda3/envs/ssd/lib/python3.6/site-packages/numba/cuda/decorators.py", line 96, in kernel_jit
    kernel.bind()
  File "/root/anaconda3/envs/ssd/lib/python3.6/site-packages/numba/cuda/compiler.py", line 489, in bind
    self._func.get()
  File "/root/anaconda3/envs/ssd/lib/python3.6/site-packages/numba/cuda/compiler.py", line 370, in get
    ptx = self.ptx.get()
  File "/root/anaconda3/envs/ssd/lib/python3.6/site-packages/numba/cuda/compiler.py", line 342, in get
    **self._extra_options)
  File "/root/anaconda3/envs/ssd/lib/python3.6/site-packages/numba/cuda/cudadrv/nvvm.py", line 464, in llvm_to_ptx
    libdevice = LibDevice(arch=opts.get('arch', 'compute_20'))
  File "/root/anaconda3/envs/ssd/lib/python3.6/site-packages/numba/cuda/cudadrv/nvvm.py", line 340, in __init__
    raise RuntimeError(MISSING_LIBDEVICE_FILE_MSG.format(arch=arch))
RuntimeError: Missing libdevice file for compute_50.
Please ensure you have package cudatoolkit 7.5.
Install package by:

    conda install cudatoolkit=7.5

**Comment by sherlockzym** [comment]
tried     sudo ln -s libdevice.10.bc libdevice.compute_50.10.bc 
But the operation returns the same error
